// Copyright 2014 AdsWizz Inc. All Rights Reserved

package com.adswizz.ms.persomap.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * <p>
 * Model class represent properties mapped to DynamoDB table. 
 * </p>
 * 
 * @author AdsWizz Inc
 *
 */
@DynamoDBTable(tableName="develDynamoTable")
public final class PersoMapUser {
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName="adsWizzUserId")
	private String adsWizzUserId;
	
	@DynamoDBAttribute(attributeName="partnerUserId")
	private String partnerUserId;
	
	@DynamoDBAttribute(attributeName="domain")
	private String domain;
	
	@DynamoDBAttribute(attributeName="idType")
	private String idType;
	
	@DynamoDBAttribute(attributeName="lastSeenDate")
	private String lastSeenDate;
	
	@DynamoDBAttribute(attributeName="creationDate")
	private String creationDate;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAdsWizzUserId() {
		return adsWizzUserId;
	}

	public void setAdsWizzUserId(String adsWizzUserId) {
		this.adsWizzUserId = adsWizzUserId;
	}

	public String getPartnerUserId() {
		return partnerUserId;
	}

	public void setPartnerUserId(String partnerUserId) {
		this.partnerUserId = partnerUserId;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getIdType() {
		return idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	public String getLastSeenDate() {
		return lastSeenDate;
	}

	public void setLastSeenDate(String lastSeenDate) {
		this.lastSeenDate = lastSeenDate;
	}

	public String getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}
	
}
